FROM golang:1.21-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app
COPY main.go .

RUN go build -ldflags="-s -w" -o app main.go

FROM scratch
WORKDIR /app

COPY --from=builder /app/app .

EXPOSE 3000

CMD ["./app"]
